namespace FizzBuzz
{
    public interface DatabaseInterface
    {
        int[] GetNumbers();
    }

    public class Database : DatabaseInterface
    {
        public int[] GetNumbers()
        {
            throw new Exception("DO NOT EDIT THIS FILE");
        }
    }
}
